version: "3.9"
services:
  shopozz-bot:
    build: .
    restart: unless-stopped
    env_file:
      - CONFIG.env
    volumes:
      - ./tracking.json:/app/tracking.json
      - ./bot.log:/app/bot.log
